config/routes.rb
Rails.application.routes.draw do
 get 'todos', to: 'todos#index'
 get 'todos/new'
 post 'todos', to: 'todos#create'
 get 'todos/list'
 get 'todos/:id', to: 'todos#show', as: 'todo'
 get 'todos/:id/edit', to: 'todos#edit', as: 'todo_edit'
 patch 'todos/:id', to: 'todos#update'
 delete 'todos/:id', to: 'todos#destroy', as: 'destroy_todo'
 get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
   validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end
  def new
    @todo = Todo.new
  end
  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end
  def show
    @todo = Todo.find(params[:id])
  end
  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
  @todo = Todo.find(params[:id])
  @todo.destroy
  redirect_to todos_path
  end

  def complete
     @todo = Todo.find(params[:id])
     @todo.completed = true
     @todo.save
     redirect_to todos_path
   end

  def list
    @todos = Todo.all
    @complete = @todos.select{ |i| i.completed == true }
    @no_complete = @todos.select { |i| i.completed == false }
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="fixed-top navbar navbar-dark bg-dark" style="margin-bottom: 100px">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000/todos"> Index <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/todos/list"> List </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="http://localhost:3000/todos/new"> Create ToDo </a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/navbar' %>
    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/edit.html.erb
<%= form_with model: @todo, local: true do |i| %>
<br>
<%= i.label :description, "Descripción ToDo" %>
<br>
<%= i.text_field :description %>
<br>
<br>
<%= i.label :completed, "Cumplimiento ToDo" %>
<br>
<%= i.check_box :completed %>
<br>
<%= i.submit "Enviar" %>
<% end %>

app/views/todos/index.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
   <div class="col-md-10">
    <% @todos.each do |i|%>
      <div class="well jumbotron">
        <h1> <%= link_to i.description, i %> </h1>
        <p> <%= i.completed %> </p>
        <p class="btn btn-danger" > <%= link_to "Borrar", i, method: :delete %> </p>
        <p class="btn btn-warning" > <%= link_to "Editar", todo_edit_path(i) %> </p>
      </div>
      <% end %>
   </div>
 </div>

app/views/todos/list.html.erb
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-4 jumbotron ">
<% @complete.each do |i| %>
    <h1> <%= i.description %> </h1>
    <p> <%= i.completed %> </p>
<% end %>
  </div>
  <div class="col-md-1">  
  </div>
  <div class="col-md- jumbotron ">
<% @no_complete.each do |i| %>
    <h1> <%= i.description %> </h1>
    <p> <%= i.completed %> </p>
<% end %>
  </div>
  <div class="col-md-1">
  </div>
</div>

app/views/todos/new.html.erb
<%= form_with model: @todo, local: true do |i| %>
<br>
<%= i.label :description, "Descripción ToDo" %>
<br>
<%= i.text_area :description %>
<br>
<br>
<%= i.label :completed, "Completado" %>
<br>
<%= i.check_box :completed %>
<br>
<%= i.submit "Enviar" %>
<% end %>

app/views/todos/show.html.erb
<h1> <%= @todo.description %> </h1>
<p> <%= @todo.completed %> </p>
<p> created <%= time_ago_in_words @todo.created_at %> ago </p>